### ISSUE TITLE
checker_attendance depends on a 3rd party plugin

### ISSUE THREAD

**Issue by adpe** [ffhs/moodle-block_course_checker#1]
Please implement a functionality to enable this check only if the `mod_attendance` plugin is installed.

**Comment by mudrd8mz** [comment]
From what I can see, the block does not actually _depend_ on the `mod_attendance` does it?

It seems it only tries to read from the attendance tables in case it actually finds some course modules associated with that module. So it does not die with error trying to read non-existing table or calling non-existing function or so.

I still think it should do a quick check (such as checking for the presence of the `/mod/attendance/version.php` or call the plugin manager to check if the Attendance is installed or not.

**Comment by adpe** [comment]
Thanks for your comment @mudrd8mz 

What I mean is, that this `checker` should be only runnable when the plugin is installed. Otherwise, it is confusing for the users.
