### ISSUE TITLE
Ignore single checks

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#17]
Add the availability to ignore single checks on the result page.

**Comment by adpe** [comment]
Hi @moleculech 

I think this is also about improvements to the link checker?

**Comment by moleculech** [comment]
@adpe 
Yes, primarly it is for the link checker. But I don't know if it is even nessessary. The improvements made to the link crawling provides very good results. I don't have the problem of wrongfully detected urls anymore.

**Comment by adpe** [comment]
Mhm I think we should check that with a course which has at the moment a lot of false detected URLs. Can you do that? Ask the LC for a example course and restore it locally on your machine and check it out.

I'm really wondering how the results will look like, if it's okay and also for the LC we can leave this issue aside.

**Comment by adpe** [comment]
Please provide your results in issue #15
