### ISSUE TITLE
Translate to german

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#18]
Translate all string to german and provide extra help for unexperienced users.

**Comment by adpe** [comment]
Hi @moleculech 

Can you please specify better which extra help you mean? Like the blue info-icons next to settings in Moodle?

As I see the German translations were accepted, see https://moodle.org/plugins/translations.php?plugin=block_course_checker.

**Comment by moleculech** [comment]
@adpe 
Exactly, like the blue info-icons. In addition inexperienced editing-teachers might not know what the block is indented for or how to start using it.

Yes the translations are accepted, but we need to translate the rest as soon as phase ii goes online.

**Comment by adpe** [comment]
What about creating a user-tour? The user-tour can be located under this plugins directory and will be installed in to Moodle. Would be much easier than insert this helpers in the logic of the plugin.

**Comment by moleculech** [comment]
@adpe 
I think thats a very good idea.

**Comment by adpe** [comment]
Hi @moleculech 

We should address the Learning Center, as they are responsible for manuals and teach instructors.
