### ISSUE TITLE
List of roles with access to manual check date and note

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#20]
Not every user should have access to the manual check date. Add a setting to define which roles have access to that form-field.

**Comment by adpe** [comment]
Hi @moleculech 

I've seen that it was not working as expected. The roles per course were not checked, so we can not guarantee, that it will work for our teachers in the course-context. I've improved your solution and add a new helper method `user_has_given_role_in_course`.

Please check out and feel free to make adaptions where needed. If it's okay you can move and close this issue.

Greets,
Adrian
