### ISSUE TITLE
Find activities with userdata

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#21]
This checker is intendet for reference oder template courses. In this kind of courses we don't want any userdata in e.g. wikis or databases.

**Comment by adpe** [comment]
Hi  @moleculech 

The checker is done and would be great to have a peer-review. It checks also forums and glossaries. As you see I added a new icon to the results. This checker is indeed not wrong when containing user-data. But he must know, that these activities entries will not be copied to the new course. 

The only way it will take this user data is when doing a manual backup of the course (including user-data) and then restore it. It can be for other users relevant, but in our case I don't know at the moment what the LC will do. I've read, that this activity can be easily imported to the module courses, so it makes sense to have e.g. a central glossary in the reference courses. And then to import these manually in to the created module courses afterwards.

Cheers,
Adrian
