### ISSUE TITLE
Compare "Maximum grade" with "Total of marks" within quizzes

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#22]
Maximum grade and Total of marks should be the same number.

**Comment by adpe** [comment]
Looks good to me @moleculech 

I've just change some stuff to be identical with other checkers, see issue https://github.com/ffhs/moodle-block_course_checker/issues/31 and particular commit https://github.com/ffhs/moodle-block_course_checker/commit/0a0791b7733b721c032e2761ea43f899889f433c and changed the resolution_link https://github.com/ffhs/moodle-block_course_checker/commit/b7b74b2d5467a0d77a64d719d688c324f33c7213.

Your check is doing what it should. Therefore done!

Cheers,
Adrian
