### ISSUE TITLE
Database activity fields

### ISSUE THREAD

**Issue by moleculech** [ffhs/moodle-block_course_checker#25]
Check if there are any data activities without fields.

**Comment by adpe** [comment]
Hi @moleculech 

We should also change the `get_link_to_modedit_page` URL and params or even better create only one function to get this link. Actual a lot of checkers have here their own nearby same method, but we can only use one to serve all.

Would be great to take this function https://github.com/ffhs/moodle-block_course_checker/blob/6f6d0985b5effe55405c8747bbf310b4e87cfa8d/classes/checkers/checker_link/checker.php#L240-L259 and use that throughout our checkers. But first we must adapt this function according the changes e.g. https://github.com/ffhs/moodle-block_course_checker/commit/8ad4e12d5e23127e17399de2981563fb518a12ea

What do you think?

Cheers,
Adrian

**Comment by moleculech** [comment]
@adpe 
Absolutely. Shall we inersert the function into locallib or create a dedicated helper class?

**Comment by adpe** [comment]
Mhm good question. I think in the `locallib.lib` it would be easier and should be enough? Please don't forget to checkout my commit 8ad4e12. With this URL path we can access nearby each module to edit it, without specifing the modtype...

**Comment by adpe** [comment]
Hi @moleculech 

As you see in this [commit](https://github.com/ffhs/moodle-block_course_checker/commit/a5afd19b91787fef7711fbba8132aa7bf0d0691b#diff-280998a802411aaccfcd0f7e797431ecL52-R56) i refactor how to loop ober given activities. Maybe we should also change that in:
- [x] checker_groups
- [x] checker_attendance

What do you think about my solution?

**Comment by moleculech** [comment]
@adpe 
I think yours is probably the solution which requires less ressources. I'll refactor checker_groups and checker_attendance
