### ISSUE TITLE
Title string letter case

### ISSUE THREAD

**Issue by mudrd8mz** [ffhs/moodle-block_course_checker#3]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings

Strings like "Course Checker", "Check Attendance Failed", "Subheading Checker Strings Whitelist" etc should all have only the first letter upper case in the default English pack for the consistency with the standard strings.

**Comment by adpe** [comment]
Hi @mudrd8mz 

Thanks for your report. When does AMOS will re-import these strings? As soon we provide a new version per  `.zip` file?

**Comment by mudrd8mz** [comment]
Yes. Any new version added to the plugins directory is automatically submitted into AMOS.
