### ISSUE TITLE
Missing Moodle_URL

### ISSUE THREAD

**Issue by dinism** [ffhs/moodle-block_course_checker#36]
I have it working.
I changed PHP from 7.1 to 7.2. I will make more tests to confirm, but manual and automatic cron are working.

But SOME "links to resolve" don't have the Moodle link.
https://i.imgur.com/Q5eKSQs.mp4
Take a look to status bar. The first 2 have correct link but the others don't.
### **Can this be done? Sentences in PT are longer than in english.**
![imagem](https://user-images.githubusercontent.com/14828021/81989729-b27a1600-9635-11ea-920e-d3a2c9ac023d.png)

**Comment by adpe** [comment]
Hi @dinism 

We've found the bug leading to the problem when Moodle is accessible by a sub page. So the plugin should now work using a `$CFG->wwwroot = 'https://yoursite.com/moodleX'.

Please test it checking out over git the plugins `master `branch. We'll include this fix in the next plugin release.

Further, your problem described showing longer texts, should be created in a separate issue. I'll close this issue, as the https://github.com/ffhs/moodle-block_course_checker/commit/71a87f161dbc7ad6935c24e609cb0c9c939f8035 fixes that.

Greets,
Adrian
