### ISSUE TITLE
 Cannot override final method core_form\dynamic_form::__construct()

### ISSUE THREAD

**Issue by Jormodn** [ffhs/moodle-block_course_checker#57]
## Summary
Moodle Version: 4.2.1+ (Build: 20230623)
Plugin Version: Newest via GIT

We had at least the old Version of this Plugin from the Moodle Directory till last week. We updated after an issue with adding blocks in courses and the plugin sends an error with references on PHP 8. Now is the same, we want to add a block on a course and the following Error appears:

PHP Fatal error:  Cannot override final method core_form\dynamic_form::__construct() in /moodle/blocks/course_checker/edit_form.php on line 43

### Actual result

After the error from above the Site shows "undefined" in a context-box and sends the error to log - no course could be added

### Expected result

the select window with blocks to add any block on the course

### Replication steps

- The selected Versions from above
- PHP 8.0
- Try to add a block to a course

**Comment by steveyyyy** [comment]
Thanks for this issue @Jormodn .
We will replicate this issue and get back to you as soon as possible.

**Comment by steveyyyy** [comment]
Hi @Jormodn

We just released an update. Please update your plugin at your earliest convenience.
